<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IBM-JQCV2F3" failures="1" tests="4" name="TestRunner.testRunner" time="94.887" errors="0" timestamp="2023-04-20T22:22:47 IST" skipped="0">
  <testcase classname="TestRunner.testRunner" name="runScenario" time="29.573"/>
  <system-out/>
  <testcase classname="TestRunner.testRunner" name="runScenario" time="12.468"/>
  <system-out/>
  <testcase classname="TestRunner.testRunner" name="runScenario" time="20.831">
    <failure message="expected [Address saved] but found [You have submitted an address that is already in your address book]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Address saved] but found [You have submitted an address that is already in your address book]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at StepDefinations.addressAddTest.check_if_address_is_sucessfully_saved(addressAddTest.java:39)
at âœ½.Check if address is sucessfully saved(file:///C:/Users/003VR5744/eclipse-workspace/E2EFramework/src/test/java/features/Amazon.feature:30)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="TestRunner.testRunner" name="runScenario" time="32.015"/>
  <system-out/>
</testsuite> <!-- TestRunner.testRunner -->
